用户管理/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views,admin

urlpatterns = [
    # path('admin/', admin.site.urls),
    #首页
    path('',views.home),

    #部门管理
    path('depart/list/',views.depart_list),
    path('depart/add/',views.depart_add),
    path('depart/delete/',views.depart_delete),
    path('depart/edit/<int:nid>/',views.depart_edit),

    #用户管理
    path('user/list/',views.user_list),
    path('user/add/',views.user_add),
    path('user/modelform/add/',views.user_modelform_add),
    path('user/edit/<int:nid>/',views.user_edit),
    path('user/delete/<int:nid>/',views.user_delete),

    #靓号管理
    path('pretty/list/',views.pretty_list),
    path('pretty/add/',views.pretty_add),
    path('pretty/edit/<int:nid>/',views.pretty_edit),
    path('pretty/delete/<int:nid>/',views.pretty_delete),

    #管理员管理
    path('admin/list/',admin.admin_list),
    path('admin/add/',admin.admin_add),
    path('admin/edit/<int:nid>/',admin.admin_edit),
    path('admin/delete/<int:nid>/',admin.admin_delete),

    #用户认证
    path('login/',views.login),
    path('loginout/',views.loginout),
    path('image/code/',views.img),

    #订单管理
    path('order/list/',views.order_list),
    path('order/add/',views.order_add),
    path('order/delete/',views.order_delete),
    path('order/detail/',views.order_detail),
    path('order/edit/',views.order_edit),

    path('chart/list/',views.chart_list),
    path('chart/bar/',views.chart_bar),



]

app01/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    """" 部门表"""
    title = models.CharField(max_length=32,verbose_name="部门标题")
    def __str__(self):
        return self.title

class UserInfo(models.Model):
    """" 员工表 """
    name = models.CharField(verbose_name="姓名",max_length=16)
    password = models.CharField(verbose_name="密码",max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    #max_digits表示account最多十位，decimal_places表示小数为2位
    account = models.DecimalField(verbose_name="账户余额",max_digits=10,decimal_places=2,default=0)
    create_time = models.DateTimeField(verbose_name="入职时间")

    depart = models.ForeignKey(verbose_name="部门",to="Department",to_field="id",on_delete=models.CASCADE)

    gender_choice = (
        (1,"男"),
        (2,"女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别",choices=gender_choice)

class PrettyNum(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name="电话",max_length=32)
    #想要允许为空，需要加上null=Ture  blank=True
    price = models.IntegerField(verbose_name="价格",default=0)

    level_choice = (
        (1,'高'),
        (2,'中'),
        (3,'低'),
    )
    level = models.SmallIntegerField(verbose_name="级别",choices=level_choice,default=1)

    status_choice = (
        (1,'已占用'),
        (2,'未占用'),
    )
    status = models.SmallIntegerField(verbose_name="状态",choices=status_choice,default=2)

class Admin(models.Model):
    """管理员表"""
    username = models.CharField(max_length=32,verbose_name="用户名")
    password = models.CharField(max_length=64,verbose_name="密码")

    def __str__(self):
        return self.username

class Order(models.Model):
    """订单表"""
    oid = models.CharField(verbose_name="订单号",max_length=64)
    title = models.CharField(verbose_name="名称",max_length=32)
    price = models.IntegerField(verbose_name="价格")

    status_choice = (
        (1,"待支付"),
        (2,"已支付"),
    )
    status = models.SmallIntegerField(verbose_name="状态",choices=status_choice,default=1)
    admin = models.ForeignKey(to="Admin",to_field="id",verbose_name="管理员",on_delete=models.CASCADE)

app01/forms.py
from django import forms
from app01.models import UserInfo,PrettyNum,Admin,Order
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from app01.encoding import md5


#利用modelform
class UserModelForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ["name","password","age","account","create_time","gender","depart"]

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        #此时self.fields.items()为元组类型，name为fields中的值，field为其对象
        for name,field in self.fields.items():
           field.widget.attrs = {"class":"form-control","placeholder":field.label}

class PrettyModelForm(forms.ModelForm):
    # #验证方式一: 利用正则表达式对字段进行校验，
    # mobile = forms.CharField(
    #     label="手机号",
    #     validators=[RegexValidator(r'^1[3-9]\d{9}$','手机号格式错误'),]
    # )

    class Meta:
        model = PrettyNum
        fields = ["mobile","price","status","level"]

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for name,field in self.fields.items():
            field.widget.attrs = {"class":"form-control","placeholder":field.label}

    #验证方式二: 钩子函数
    def clean_mobile(self):
        moble_text = self.cleaned_data['mobile']
        if len(moble_text) != 11 :
            #验证不通过
            raise ValidationError("手机号格式错误")
        return moble_text

class AdminModel(forms.ModelForm):
    confirm_password = forms.CharField(label="确认密码",widget=forms.PasswordInput(render_value=True))
    class Meta:
        model = Admin
        fields = ["username","password","confirm_password"]
        widgets = {
            "password":forms.PasswordInput(render_value=True)
        }

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for name,field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}


    #利用钩子函数对密码进行加密
    def clean_password(self):
        password = self.cleaned_data['password']
        return md5(password)

     # 钩子函数
    def clean_confirm_password(self):
        confirm = md5(self.cleaned_data['confirm_password'])
        password = self.cleaned_data['password']
        if confirm != password:
            raise ValidationError("密码不一致")
        return confirm

#利用form
class LoginForm(forms.Form):
    username = forms.CharField(label="用户名",widget=forms.TextInput(attrs={"class":"form-control","placeholder":"用户名"}))
    password = forms.CharField(label="密码",widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"密码"},render_value=True))
    code = forms.CharField(label="验证码",widget=forms.TextInput(attrs={"class":"form-control","placeholder":"验证码"}))

    def clean_password(self):
        password = self.cleaned_data["password"]
        return md5(password)


class OrderModelForm(forms.ModelForm):
    class Meta:
        model = Order
        # fields = "__all__"选择所有字段
        exclude = ["oid","admin"] #排除oid字段

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for name,field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}

app01/views.py
from django.shortcuts import render,redirect,HttpResponse
from app01.models import Department,UserInfo,PrettyNum,Admin,Order
from app01.forms import UserModelForm,PrettyModelForm,LoginForm,OrderModelForm
from django.utils.safestring import mark_safe
from code import check_code
from io import BytesIO
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import random
from datetime import datetime
# Create your views here.
def home(request):
    return HttpResponse("首页")


def depart_list(request):
    """"部门列表"""
    queryset = Department.objects.all()
    return render(request,"depart_list.html",{"queryset":queryset})

def depart_add(request):
    """添加部门"""
    if request.method == "GET":
        return render(request,"depart_add.html")
    else:
        name = request.POST.get("name")
        Department.objects.create(title=name)
        return redirect("/depart/list/")

def depart_delete(request):
    """删除部门"""
    nid = request.GET.get("nid")
    Department.objects.filter(id=nid).delete()
    return redirect("/depart/list")

def depart_edit(request,nid):
    if request.method == "GET":
        edit_model = Department.objects.filter(id=nid).first()
        return render(request,"depart_edit.html",{"edit_model":edit_model})
    else:
        title = request.POST.get("name")
        Department.objects.filter(id=nid).update(title=title)
        return redirect("/depart/list")


def user_list(request):
    queryset = UserInfo.objects.all()
    return render(request,"user_list.html",{"queryset":queryset})

def user_add(request):
    if request.method == "GET":
        context = {
            "gender_choice":UserInfo.gender_choice,
            "depart_list":Department.objects.all()
        }
        return render(request,"user_add.html",context)
    else:
        name = request.POST.get("name")
        password = request.POST.get("password")
        age = request.POST.get("age")
        account = request.POST.get("account")
        create_time = request.POST.get("create_time")
        gender = request.POST.get("gender")
        depart = request.POST.get("depart")

        UserInfo.objects.create(name=name,password=password,age=age,account=account,create_time=create_time,gender=gender,depart_id=depart)
        return redirect("/user/list/")

def user_modelform_add(request):
    if request.method == "GET":
        form = UserModelForm()
        return render(request,"user_modelform_add.html",{"form":form})
    else:
        form = UserModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("/user/list/")
        else:
            return render(request,"user_modelform_add.html",{"form":form})

def user_edit(request,nid):
    if request.method == "GET":
        model = UserInfo.objects.filter(id=nid).first()
        form = UserModelForm(instance=model)
        return render(request,"user_edit.html",{"form":form})
    else:
        model = UserInfo.objects.filter(id=nid).first()
        form = UserModelForm(data=request.POST,instance=model)
        if form.is_valid():
            form.save()
            return redirect("/user/list")
        else:
            return render(request,"user_edit.html",{"form":form})

def user_delete(request,nid):
    UserInfo.objects.filter(id=nid).first().delete()
    return redirect("/user/list/")

def pretty_list(request):
    """靓号列表"""
    #搜索功能，根据电话搜索
    data_dict = {}
    search_data = request.GET.get('q','')
    if search_data:
        data_dict['mobile__contains'] = search_data

    #分页
    page = int(request.GET.get('page',1))
    page_size = 10
    start = (page-1) * page_size #起始
    end = page * page_size #结束

    queryset = PrettyNum.objects.filter(**data_dict).order_by('-level')[start:end]
    #获取数据库页数
    total_count = PrettyNum.objects.all().count()
    total_page_count , div =divmod(total_count,page_size)
    if div:
        total_page_count += 1

    #计算出当前页的前五页，后五页
    plus = 5
    # 如果数据库中的页不足11页
    if total_page_count <= plus*2+1:
        start_page = 1
        end_page = total_page_count
    else:
        #数据库中的数据大于11页
        #且当前页小于等于5
        if page <= plus:
            start_page = 1
            end_page = 2*plus +1
        else:
            if page > total_page_count-5:
                start_page = total_page_count - 2*plus
                end_page =  total_page_count
            else:
                start_page = page - plus
                end_page = page + plus


    #页码
    page_str_list = []
    #上一页
    if page>1:
        pre = '<li class="active"><a href="?page={}">上一页</a></li>'.format(page-1)
        page_str_list.append(pre)

    for i in range(start_page,end_page+1):
        if i == page:
            ele = '<li class="active"><a href="?page={}">{}</a></li>'.format(i, i)
        else:
            ele = '<li><a href="?page={}">{}</a></li>'.format(i,i)
        page_str_list.append(ele)
    #下一页
    if page< total_page_count:
        pre = '<li class="active"><a href="?page={}">下一页</a></li>'.format(page + 1)
        page_str_list.append(pre)

    page_string = mark_safe("".join(page_str_list))
    return render(request,"pretty_list.html",{"queryset":queryset,"search_data":search_data,"page_string":page_string})


def pretty_add(request):
    if request.method == "GET":
        form = PrettyModelForm()
        return render(request,"pretty_add.html",{"form":form})
    else:
        form = PrettyModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("/pretty/list/")
        else:
            return render(request,"pretty_add.html",{"form":form})


def pretty_edit(request,nid):
    model = PrettyNum.objects.filter(id=nid).first()
    if request.method == "GET":
        form = PrettyModelForm(instance=model)
        return render(request,"pretty_edit.html",{"form":form})
    else:
        form = PrettyModelForm(data=request.POST,instance=model)
        if form.is_valid():
            form.save()
            return redirect("/pretty/list/")
        else:
            return render(request,"pretty_edit.html",{"form":form})


def pretty_delete(request,nid):
    PrettyNum.objects.filter(id=nid).first().delete()
    return redirect("/pretty/list/")


def login(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request,"login.html",{"form":form})
    else:
        form = LoginForm(data=request.POST)
        if form.is_valid():
            #因为form中有code字段，而数据库中没有，所有做验证时不能将code放进去验证
            input_code = form.cleaned_data.pop("code")
            #获取之前放入session中的img_code
            code = request.session.get("img_code","")
            if code.upper() != input_code.upper():
                #给form.code.error添加错误信息
                form.add_error("code","验证码错误")
                return render(request,"login.html",{"form":form})

            #form.clean_data = {"username":"sss","password":"dadnalkdhnaoldhnao"}

            #当LoginForm中的字段名等于MODEL里的字段名时，可以将**form.cleaned_data传入filter中，作为校验
            obj = Admin.objects.filter(**form.cleaned_data).first()
            if obj:
                #删除掉之前session中的验证码，防止使用此验证码多次登录
                request.session.clear()
                request.session["info"] = {"id":obj.id,"username":obj.username}
                #重新设置session的超时时间为7天
                request.session.set_expiry(60*60*24*7)
                return redirect("/depart/list/")
            else:
                form.add_error("password","用户名或密码错误")
                return render(request, "login.html", {"form": form})
        else:
            return render(request,"login.html",{"form":form})


def loginout(request):
    request.session.clear()
    return redirect('/login/')


def img(request):
    """生成图片验证码"""
    #接收生成的图片和图片的验证码
    img , code_string = check_code()
    #将图片验证码写入到自己的session中，以便校验
    request.session["img_code"] = code_string
    #给sess设置60s超时
    request.session.set_expiry(60)
    #创建1个IO对象
    stream = BytesIO()
    # 把图片img保存到内存
    img.save(stream,'png')
    #getvalue()获取图片信息
    return HttpResponse(stream.getvalue())


def order_list(request):
    queryset = Order.objects.all().order_by("-id")
    form = OrderModelForm()
    return render(request,"order_list.html",{"form":form,"queryset":queryset})

@csrf_exempt
def order_add(request):
    """新建订单ajax"""
    form = OrderModelForm(data=request.POST)
    if form.is_valid():
        form.instance.oid = datetime.now().strftime("%Y%m%d%H%M%S") + str(random.randint(1000,9999))
        form.instance.admin_id = request.session["info"]["id"]
        form.save()
        return JsonResponse({"status":True})
    return JsonResponse({"status":False,"error":form.errors})


def order_delete(request):
    uid = request.GET.get("uid")
    exists = Order.objects.filter(id=uid).exists()
    if not exists:
        return JsonResponse({"status":False,"error":"删除失败,数据不存在"})
    Order.objects.filter(id=uid).delete()
    return JsonResponse({"status":True})


def order_detail(request):
    """根据uid获取当前行数据"""
    uid = request.GET.get("uid")
    #加上.values后生成的row_dict是一个字典{"status":"已支付"}
    row_dict = Order.objects.filter(id=uid).values("status","title","price").first()
    if not row_dict:
        return JsonResponse({"status": False, "error": "数据不存在"})
    else:
        data = {
            "status":True,
            "result":row_dict
        }
        return JsonResponse(data)

@csrf_exempt
def order_edit(request):
    """编辑订单"""
    uid = request.GET.get("uid")
    row_object = Order.objects.filter(id=uid).first()
    if not row_object:
        return JsonResponse({"status":False,"tips":"数据不存在。"})
    else:

app01/templates/admin_add.html
{% extends "base.html" %}

{% block content %}
  <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">添加管理员</h3>
      </div>
      <div class="panel-body">
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group" >
            <label>{{ field.label }}</label>
              {{ field }}
              <span style="color: red">{{ field.errors.0 }}</span>
          </div>
          {% endfor %}
          <div class="form-group">
              <button type="submit" class="btn btn-primary" style= "text-align: left " >保存</button>
          </div>

        </form>
      </div>
    </div>
{% endblock %}

app01/templates/admin_edit.html
{% extends "base.html" %}

{% block content %}
  <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">编辑管理员</h3>
      </div>
      <div class="panel-body">
        <form class="form-horizontal" method="post" >
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group" >
            <label>{{ field.label }}</label>
              {{ field }}
              <span style="color: red">{{ field.errors.0 }}</span>
          </div>
          {% endfor %}
          <div class="form-group">
              <button type="submit" class="btn btn-primary" style= "text-align: left " >保存</button>
          </div>

        </form>
      </div>
    </div>
{% endblock %}

app01/templates/admin_list.html
{% extends "base.html" %}

{% block content %}
 <div style="margin-bottom: 10px">
      <a class="btn btn-success" href="/admin/add/">新建管理员</a>
    </div>
    <div>
      <div class="bs-example" data-example-id="panel-without-body-with-table">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
        管理员列表
      </div>

      <!-- Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>用户名</th>
            <th>密码</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
         {% for obj in queryset %}
          <tr>
            <th scope="row">{{ obj.id }}</th>
            <td>{{ obj.username }}</td>
            <td>******</td>
            <td>
              <a href="/admin/edit/{{ obj.id }}/" class="btn btn-primary btn-xs">编辑</a>
              <a href="/admin/delete/{{ obj.id }}/" class="btn btn-danger btn-xs" >删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
    </div>
{% endblock %}

app01/templates/chart_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">折线图</div>
    <div class="panel-body">
      图图图
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
        <div class="panel panel-default">
    <div class="panel-heading">柱状图</div>
    <div class="panel-body">
      <div id="m2" style="width: 100%;height: 400px"></div>
    </div>
  </div>
    </div>

    <div class="col-sm-4">
        <div class="panel panel-default">
    <div class="panel-heading">饼图</div>
    <div class="panel-body">
      图图图
    </div>
  </div>
    </div>
  </div>
  </div>


<script src="{% static 'js/echarts.js' %}"></script>
<script type="text/javascript">
$(function (){
    initBar();
})

/**
 * 初始化柱状图
 */

function initBar(){
    //基于准备好的dom，初始化echarts实例
var mychart = echarts.init(document.getElementById("m2"));

//指定图表的配置项和数据
var option = {
    title:{
        text:'ECharts 入门实例'
    },
    tooltip:{},
    legend:{
        data:[]
    },
    xAxis:{
        data:[]
    },
    yAxis: {},
    series : []
};

$.ajax({
    url:"/chart/bar/",
    type:"get",
    dataType:"JSON",
    success:function (res){
        //将后台返回的数据更新到option中
        if (res.status){
            option.legend.data = res.data.legend;
            option.xAxis.data = res.data.xAxis;
            option.series = res.data.series;
        //使用刚指定的配置项和数据显示图片
        mychart.setOption(option);
        }
    }
})
}

</script>
{% endblock %}

app01/templates/depart_add.html
{% extends "base.html" %}
{% block content %}
  <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">新建部门</h3>
      </div>
      <div class="panel-body">
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">标题</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="name" placeholder="标题">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">保存</button>
            </div>
          </div>
        </form>
      </div>
    </div>
{% endblock %}

app01/templates/depart_edit.html
{% extends "base.html" %}

{% block content %}
 <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">编辑部门</h3>
      </div>
      <div class="panel-body">
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">标题</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="name" value="{{ edit_model.title }}">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">保存</button>
            </div>
          </div>
        </form>
      </div>
    </div>
{% endblock %}

app01/templates/depart_list.html
{% extends "base.html" %}

{% block content %}
 <div style="margin-bottom: 10px">
      <a class="btn btn-success" href="/depart/add/">新建部门</a>
    </div>
    <div>
      <div class="bs-example" data-example-id="panel-without-body-with-table">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
        部门列表
      </div>

      <!-- Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>部门名称</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
         {% for obj in queryset %}
          <tr>
            <th scope="row">{{ obj.id }}</th>
            <td>{{ obj.title }}</td>
            <td>
              <a href="/depart/edit/{{ obj.id }}/" class="btn btn-primary btn-xs">编辑</a>
              <a href="/depart/delete/?nid={{ obj.id }}" class="btn btn-danger btn-xs" >删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
    </div>
{% endblock %}

app01/templates/pretty_add.html
{% extends "base.html" %}

{% block content %}
  <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">添加靓号</h3>
      </div>
      <div class="panel-body">
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group" >
            <label>{{ field.label }}</label>
              {{ field }}
              <span style="color: red">{{ field.errors.0 }}</span>
          </div>
          {% endfor %}
          <div class="form-group">
              <button type="submit" class="btn btn-primary" style= "text-align: left " >保存</button>
          </div>

        </form>
      </div>
    </div>
{% endblock %}

app01/templates/pretty_edit.html
{% extends "base.html" %}

{% block content %}
  <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">编辑用户</h3>
      </div>
      <div class="panel-body">
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group" >
            <label>{{ field.label }}</label>
              {{ field }}
              <span style="color: red">{{ field.errors.0 }}</span>
          </div>
          {% endfor %}
          <div class="form-group">
              <button type="submit" class="btn btn-primary" style= "text-align: left " >保存</button>
          </div>

        </form>
      </div>
    </div>
{% endblock %}

app01/templates/pretty_list.html
{% extends "base.html" %}

{% block content %}
  <div style="margin-bottom: 10px">
      <a class="btn btn-success" href="/pretty/add/">新建靓号</a>


      <div  style="width: 300px;float: right">
        <form method="get">
          <div class="input-group">
        <input type="text" class="form-control" placeholder="搜索" value="{{ search_data }}" name="q">
        <span class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </button>
        </span>
            </div>
        </form>
      </div><!-- /input-group -->
    </div>

    <div>
      <div class="bs-example" data-example-id="panel-without-body-with-table">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
        用户列表
      </div>

      <!-- Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>电话</th>
            <th>价格</th>
            <th>级别</th>
            <th>状态</th>
          </tr>
        </thead>
        <tbody>
        {% for obj in queryset %}
          <tr>
            <th scope="row">{{ obj.id }}</th>
            <td>{{ obj.mobile }}</td>
            <td>{{ obj.price }}</td>
            <td>{{ obj.get_level_display }}</td>
            <td>{{ obj.get_status_display }}</td>
            <td>
              <a href="/pretty/edit/{{ obj.id }}/" class="btn btn-primary btn-xs">编辑</a>
              <a href="/pretty/delete/{{ obj.id }}/" class="btn btn-danger btn-xs" >删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
    <div style="text-align: center">
      <ul class="pagination " >
        {{ page_string }}
      </ul>
    </div>

    </div>
{% endblock %}

app01/templates/user_list.html
{% extends "base.html" %}

{% block content %}
  <div style="margin-bottom: 10px">
      <a class="btn btn-success" href="/user/add/">新建用户</a>
  <a class="btn btn-success" href="/user/modelform/add">新建用户ModelForm</a>
    </div>
  
    <div>
      <div class="bs-example" data-example-id="panel-without-body-with-table">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
        用户列表
      </div>

      <!-- Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>密码</th>
            <th>年龄</th>
            <th>账户余额</th>
            <th>入职时间</th>
            <th>所属部门</th>
            <th>性别</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        {% for obj in queryset %}
          <tr>
            <th scope="row">{{ obj.id }}</th>
            <td>{{ obj.name }}</td>
            <td>{{ obj.password }}</td>
            <td>{{ obj.age }}</td>
            <td>{{ obj.account }}</td>
            <td>{{ obj.create_time|date:"Y-m-d H:i:s" }}</td>
            <td>{{ obj.depart.title }}</td>
            <td>{{ obj.get_gender_display }}</td>
            <td>
              <a href="/user/edit/{{ obj.id }}/" class="btn btn-primary btn-xs">编辑</a>
              <a href="/user/delete/{{ obj.id }}" class="btn btn-danger btn-xs" >删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
    </div>
{% endblock %}

app01/templates/user_modelform_add.html
{% extends "base.html" %}

{% block content %}
  <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">添加用户</h3>
      </div>
      <div class="panel-body">
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group" >
            <label>{{ field.label }}</label>
              {{ field }}
              <span style="color: red">{{ field.errors.0 }}</span>
          </div>
          {% endfor %}
          <div class="form-group">
              <button type="submit" class="btn btn-primary" style= "text-align: left " >保存</button>
          </div>

        </form>
      </div>
    </div>
   <script>
    $(function (){
        $('#id_create_time').datetimepicker({
            format: 'yyyy-mm-dd',
            startDate:'0',
            language:'zh-CN',
            autoclose:true
        });
    })
  </script>
{% endblock %}